<!DOCTYPE html>
<html lang="ps" dir="rtl">
<head>
    <meta charset="UTF-8">
    <style>
        @page { margin: 1cm; }
        body {
            font-family: 'bahij_nazanin', 'dejavusans', 'Times New Roman', serif;
            color: #1e293b;
            background: #fff;
            margin: 0;
            line-height: 1.45;
        }
        .header-table {
            width: 100%;
            margin-bottom: 20px;
        }
        .header-table td {
            border-bottom: 1px solid #2d5a27;
            padding-bottom: 8px;
            vertical-align: bottom;
        }
        .header-meta {
            color: #2d5a27;
            font-size: 18px;
            margin-top: 40px;
            font-weight: 500;
        }
        .uni-name-ps {
            font-weight: bolder;
            color: #2d5a27;
            font-size: 26px;
            margin: 0;
            line-height: 1.35;
        }
        .report-title-container {
            text-align: center; margin: 15px 0 15px;
        }
        .report-title {
            background: #d9f0c5; color: #080808;
            padding: 6px 24px;
            display: inline-block;
            font-size: 20px;
            font-weight: bold;
            border-radius: 30px;
        }
        .metric-subtext { font-size: 18px; color: #090909; margin-top: 6px;}
        .academic-table {
            width: 100%; border-collapse: collapse; font-size: 8px; direction: rtl;
        }
        .academic-table th, .academic-table td {
            border: 0.8px solid #cfe3c0; padding: 5px 3px; text-align: center;
        }
        .academic-table th {
            background: #e8f5e1; color: #1e4620; font-weight: bold;
            font-size: 16px; text-transform: uppercase;
        }
        .academic-table td { color: #000000; font-size: 14px }
        .academic-table tbody tr:nth-child(even) td { background: #fefce8; }
        .academic-table tbody tr:nth-child(odd) td { background: #f4f9f0; }
        .footer { margin-top: 40px; }
        .signature-block {
            float: left; width: 200px; border-top: 1px solid #2d5a27;
            padding-top: 15px; font-size: 10px; text-align: center;
            color: #2d5a27;
        }
        .footer-line {
            border-top: 1px solid #cfe3c0; margin-top: 20px;
            padding-top: 8px; font-size: 9px; color: #6c7a91;
            text-align: center; clear: both;
        }
    </style>
</head>
<body>

<table class="header-table" style="width:100%;">
    <tr>
        <td style="width:30%; text-align:right;">
            <img src="{{ public_path('images/ministry.png') }}" style="width: 85px; margin-bottom: 8px;">
            <div class="header-meta"><strong>نیټه:</strong> {{ $date }}</div>
        </td>
        <td style="width:40%; text-align:center;">
            <div class="uni-name-ps">د افغانستان اسلامی امارت</div>
            <div style="font-size: 18px; color: #4a7c3b; font-weight: bold;">د لوړو زده کړو وزارت</div>
            <div style="font-size: 16px; color: #4a7c3b; font-weight: bold;">کندهار پوهنتون</div>
            <div style="font-size: 14px; color: #4a7c3b; font-weight: bold;">د علمې چارو معاونیت</div>
            <div style="font-size: 14px; color: #4a7c3b; font-weight: bold;">د استادانو د تقرر او علمي ترفيعاتو آمريت</div>

        </td>
        <td style="width:30%; text-align:left;">
            <img src="{{ public_path('images/KDRU_LOGO.png') }}" style="width: 85px; margin-bottom: 8px;">
            <div class="header-meta"><strong>REF NO:</strong> KU-EDU-{{ date('Y') }}-{{ rand(100,999) }}</div>
        </td>
    </tr>
</table>

<div class="report-title-container">
    <div class="report-title">د کندهار پوهنتون د علمي کادر د غړو احصائيوي جدول (۱۴۰۵) د څانګي، پوهنځي، علمي رتبې او د تحصيلي سويې په تفکيک</div>
    <div class="metric-subtext">{{ $filterSummary }}</div>
</div>

<table class="academic-table">
    <thead>
        <tr>
            @foreach($columns as $col)
                <th>{{ $col }}</th>
            @endforeach
        </tr>
    </thead>
    <tbody>
        @forelse($rows as $row)
        <tr>
            @foreach($row as $cell)
                <td>{{ $cell }}</td>
            @endforeach
        </tr>
        @empty
        <tr>
            <td colspan="{{ count($columns) }}" style="text-align:center; padding: 20px;">هیچ معلومات نشته</td>
        </tr>
        @endforelse
    </tbody>
</table>

<div class="footer">
    <div class="signature-block">
        د علمی څیړنو مرستیال<br>
        <p style="font-size:10px; font-weight:700;">پوهنيار دوکتور رحمت الله پښتون</p>
    </div>
    <div class="footer-line">
        نوټ: دغه جدول په اتوماتیک ډول د ډیټابیس څخه د علمي احصایې په موخه ترتیب سوی دی.<br>
        This is an official report generated by Kandahar University Research Database.
    </div>
</div>

</body>
</html>